server:
  port: 8081

spring:
  application:
    name: springboot-basic-segwang
  datasource:
    url: jdbc:mysql://localhost:3306/securitymember?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  issuer: test@naver.com
  secret_key: 1CUkGbcRHun/pzZ7iX5GLk4AswnEZor6gz1bu9tkfL7bh7x9O40g34qgkdOoct3CyQLh8Rb0nQ5oVKhv2/Ojvw==